### ISSUE TITLE
Parity db

### ISSUE THREAD

**Issue by udaykiran1809** [OpenBlockchainLab/substrate_guide#1]
![IMG-20210610-WA0000.jpeg](https://user-images.githubusercontent.com/70482052/121878779-b9d48d00-cd29-11eb-980b-c153e2789f8a.jpeg)

**Comment by stanly-johnson** [comment]
Can you show the output you get after running `rustup show`

**Comment by udaykiran1809** [comment]
Problem solved after reinstalling vs code.
